{ config, lib, pkgs, ... }:

with lib;

let

  cfg = config.programs.zen;

  mkOverridesFile = prefs: ''
    // Generated by Home Manager.

    ${concatStrings (mapAttrsToList (name: value: ''
      defaultPref("${name}", ${builtins.toJSON value});
    '') prefs)}
  '';

  modulePath = [ "programs" "zen" ];

  mkFirefoxModule = import ./firefox/mkFirefoxModule.nix;

in {
  meta.maintainers = [ maintainers._0x006e ];

  imports = [
    (mkFirefoxModule {
      inherit modulePath;
      name = "Zen";
      description = "";
      wrappedPackageName = "zen-browser-bin";
      unwrappedPackageName = "zen-browser-unwrapped";

      platforms.linux = {
        vendorPath = ".zen";
        configPath = ".zen";
      };
      platforms.darwin = {
        vendorPath = "Library/Application Support/Zen";
        configPath = "Library/Application Support/Zen";
      };

      enableBookmarks = false;
    })
  ];

  config = mkIf cfg.enable {
    assertions = [
      (lib.hm.assertions.assertPlatform "programs.zen" pkgs lib.platforms.linux)
    ];

  };
}
